version: '3'
services:
  develop:
    build: .
    volumes:
     - .:/home/node/paper-calendar
    ports:
     - '4000-4010:4000-4010'
    environment:
     - TZ=America/Sao_Paulo
     - DISPLAY=unix$DISPLAY
    network_mode: 'host'
